export const GET_TYPES = "GET_TYPES";

// Country

export const GET_COUNTRY_LIST= "GET_COUNTRY_LIST";
export const VIEW_COUNTRY_LIST= "VIEW_COUNTRY_LIST";

// State
export const GET_STATE_LIST= "GET_STATE_LIST";
export const VIEW_STATE_LIST= "VIEW_STATE_LIST";

// City

export const VIEW_CITY_LIST = "VIEW_CITY_LIST";
export const GET_CITY_LIST= "GET_CITY_LIST";

export const GET_SEA_LIST= "GET_SEA_LIST";
export const VIEW_SEA_LIST= "VIEW_SEA_LIST";

export const VIEW_AIRPORT_LIST="VIEW_AIRPORT_LIST"
export const GET_AIRPORT_LIST="GET_AIRPORT_LIST"

export const VIEW_HSN_LIST="VIEW_HSN_LIST"
export const GET_HSN_LIST="GET_HSN_LIST"

export const GET_LICENSE_LIST="GET_LICENSE_LIST"
export const VIEW_LICENSE_LIST="VIEW_LICENSE_LIST"

export const GET_CARGO_LIST="GET_CARGO_LIST"
export const VIEW_CARGO_LIST="VIEW_CARGO_LIST"

// Dimension

export const GET_DIMENSION_LIST="GET_DIMENSION_LIST"
export const VIEW_DIMENSION_LIST="VIEW_DIMENSION_LIST"

export const GET_SHIPMENT_LIST= "GET_SHIPMENT_LIST"
export const GET_REASON_LIST = 'GET_REASON_LIST';
